let ctx=null,master=null,timer=null,enabled=true,musicGain=null;
const ensure=()=>{if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.22;master.connect(ctx.destination);musicGain=ctx.createGain();musicGain.gain.value=.14;musicGain.connect(master)}if(ctx.state==='suspended')ctx.resume();return ctx};
export const setSoundEnabled=v=>{enabled=v;if(!v){stopMusic();window.speechSynthesis?.cancel()}}; export const isSoundEnabled=()=>enabled;
const tone=(freq,dur=.16,type='sine',vol=1,when=0,target='fx')=>{if(!enabled)return;const c=ensure(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,c.currentTime+when);g.gain.exponentialRampToValueAtTime(Math.max(.0002,.18*vol),c.currentTime+when+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+when+dur);o.connect(g);g.connect(target==='music'?musicGain:master);o.start(c.currentTime+when);o.stop(c.currentTime+when+dur+.03)};
export const clickSound=()=>tone(660,.08,'sine',.35); export const correctSound=()=>{tone(523,.12,'triangle',.65);tone(659,.12,'triangle',.65,.1);tone(784,.2,'triangle',.75,.2)}; export const wrongSound=()=>{tone(240,.12,'sine',.25);tone(190,.18,'sine',.2,.12)}; export const pieceSound=()=>{tone(740,.07,'sine',.3);tone(880,.09,'sine',.28,.06)}; export const winSound=()=>[523,659,784,1047].forEach((n,i)=>tone(n,.25,'triangle',.7,i*.13));
const themes=[[261.6,329.6,392,329.6,440,392,329.6,293.7],[293.7,349.2,440,349.2,493.9,440,349.2,329.6],[329.6,392,493.9,440,392,329.6,293.7,329.6],[261.6,392,349.2,329.6,293.7,329.6,392,523.3],[392,440,523.3,440,587.3,523.3,440,392],[349.2,440,523.3,493.9,440,392,349.2,392],[440,523.3,659.3,587.3,523.3,493.9,440,523.3],[392,493.9,587.3,523.3,493.9,440,392,349.2]];
export const startMusic=(theme=0)=>{stopMusic();if(!enabled)return;ensure();const notes=themes[Math.abs(theme)%themes.length];let i=0;const play=()=>{tone(notes[i%notes.length],.34,'sine',.34,0,'music');if(i%4===0)tone(notes[i%notes.length]/2,.46,'triangle',.13,0,'music');i++};play();timer=setInterval(play,430)}; export const stopMusic=()=>{if(timer){clearInterval(timer);timer=null}};
const femaleHints=['female','mujer','monica','paulina','sabina','helena','elvira','dalia','sofia','luciana','maria']; const maleHints=['male','hombre','jorge','pablo','diego','raul','carlos','alvaro','andres','mateo'];
function chooseVoice(gender){const voices=window.speechSynthesis?.getVoices?.()||[];const spanish=voices.filter(v=>/^es/i.test(v.lang));const pool=spanish.length?spanish:voices;const hints=gender==='nina'?femaleHints:maleHints;return pool.find(v=>hints.some(h=>v.name.toLowerCase().includes(h)))||pool[gender==='nina'?1:0]||pool[0]||null}
export function speak(text,gender='nino',{rate=1.02,pitch}={}){if(!enabled||!('speechSynthesis'in window))return;ensure();if(musicGain)musicGain.gain.setTargetAtTime(.035,ctx.currentTime,.05);window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-PE';u.rate=rate;u.pitch=pitch??(gender==='nina'?1.12:.96);u.volume=1;const v=chooseVoice(gender);if(v)u.voice=v;u.onend=()=>{if(musicGain)musicGain.gain.setTargetAtTime(.14,ctx.currentTime,.15)};u.onerror=u.onend;window.speechSynthesis.speak(u)}
export const speakCorrect=g=>speak(['¡Sí! ¡Muy bien!','¡Excelente! ¡Lo hiciste genial!','¡Súper! ¡Respuesta correcta!'][Math.floor(Math.random()*3)],g,{rate:1.08}); export const speakWrong=g=>speak('¡Casi! Inténtalo otra vez. ¡Tú puedes!',g,{rate:1.05}); export const speakPuzzleComplete=g=>speak('¡Rompecabezas completado! ¡Lo lograste! ¡Muy bien!',g,{rate:1.04});
const words=['cero','una','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','once','doce','trece','catorce','quince','dieciséis','diecisiete','dieciocho','diecinueve','veinte'];
const num=n=>words[n]??String(n); const noun=(item,n)=>n===1?item.one:item.many; const quantified=(item,n)=>n===1?`${item.gender==='f'?'una':'un'} ${item.one}`:`${num(n)} ${item.many}`;
export const speakMathInstruction=(type,g,a,b,item={one:'dibujo',many:'dibujos',gender:'m'})=>{let t;if(type==='sum')t=`Tenemos ${quantified(item,a)}, más ${quantified(item,b)}. ¿Cuántos ${item.many} tenemos en total?`;else if(type==='sub')t=`Tenemos ${quantified(item,a)}. Quitamos ${quantified(item,b)}. ¿Cuántos ${item.many} quedan?`;else if(type==='count')t=`¿Cuántos ${item.many} hay? Cuenta con atención.`;else t=`Mira los números. ${num(a)}, ${num(a+b)}. ¿Qué número sigue?`;speak(t,g,{rate:1.04})};
export const speakPuzzleInstruction=g=>speak('¡Vamos a armar el dibujo! Toca una pieza y JUMATI iluminará automáticamente el lugar donde va.',g,{rate:1.03});
