import React, {useEffect,useMemo,useState} from 'react';
import {getUsers,saveUser,login,logout,session,getProgress,saveProgress} from './services/storage';
import {difficulties,puzzleList,gridFor,puzzleSvgData} from './data/puzzles';
import {clickSound,correctSound,wrongSound,pieceSound,winSound,startMusic,stopMusic,setSoundEnabled,isSoundEnabled,speakCorrect,speakWrong,speakPuzzleComplete,speakMathInstruction,speakPuzzleInstruction,speak} from './services/sound';

const Logo=()=> <div className="logo"><span>J</span><span>U</span><span>M</span><span>A</span><span>T</span><span>I</span></div>;
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const objects=[
 {icon:'🍎',one:'manzana',many:'manzanas',gender:'f'}, {icon:'🐶',one:'perrito',many:'perritos',gender:'m'},
 {icon:'🐠',one:'pez',many:'peces',gender:'m'}, {icon:'🦋',one:'mariposa',many:'mariposas',gender:'f'},
 {icon:'🚗',one:'carrito',many:'carritos',gender:'m'}, {icon:'⭐',one:'estrella',many:'estrellas',gender:'f'},
 {icon:'🎈',one:'globo',many:'globos',gender:'m'}, {icon:'🐰',one:'conejito',many:'conejitos',gender:'m'},
 {icon:'🍌',one:'plátano',many:'plátanos',gender:'m'}, {icon:'🐱',one:'gatito',many:'gatitos',gender:'m'}
];
const randomObject=()=>objects[Math.floor(Math.random()*objects.length)];
const initialChallenge=(type='sum')=>{const item=randomObject();let a=2,b=1,op='+';if(type==='sub'){a=5;b=2;op='-'}if(type==='count'){a=4;b=0;op='count'}if(type==='seq'){a=1;b=1;op='seq'}return {a,b,op,answer:'',feedback:'',item,locked:false}};

function App(){
 const s=session();
 const remembered=(()=>{try{return JSON.parse(localStorage.getItem('jumati_remember')||'null')}catch{return null}})();
 const [screen,setScreen]=useState(s?'menu':'home'),[current,setCurrent]=useState(s),[msg,setMsg]=useState('');
 const [form,setForm]=useState({name:'',user:'',password:'',age:'5',gender:'nino',avatar:'🦁'});
 const [auth,setAuth]=useState({user:remembered?.user||'',password:remembered?.password||''});
 const [remember,setRemember]=useState(Boolean(remembered)),[showPassword,setShowPassword]=useState(false);
 const [selectedPuzzle,setSelectedPuzzle]=useState(null),[difficulty,setDifficulty]=useState(8),[puzzleKey,setPuzzleKey]=useState(0);
 const [math,setMath]=useState(initialChallenge('sum')),[gameType,setGameType]=useState('sum');
 const progress=current?getProgress(current.user):{stars:0,completed:[],mathCorrect:0};

 useEffect(()=>{
   const musicalScreens={menu:0,games:1,puzzles:2,difficulty:2,achievements:3,progress:3};
   if(musicalScreens[screen]===undefined)return;
   startMusic(musicalScreens[screen]+(current?.gender==='nina'?4:0));
   return ()=>stopMusic();
 },[screen,current?.gender]);
 useEffect(()=>{
   if(screen!=='math')return;
   const theme={sum:0,sub:1,count:2,seq:3}[gameType]??0;
   startMusic(theme+(current?.gender==='nina'?4:0));
   const t=setTimeout(()=>speakMathInstruction(gameType,current?.gender,math.a,math.b,math.item),350);
   return ()=>{clearTimeout(t);stopMusic();window.speechSynthesis?.cancel();};
 },[screen,gameType]);

 const go=x=>{clickSound();setMsg('');setScreen(x)};
 const doLogin=e=>{e.preventDefault();const u=login(auth.user,auth.password);if(!u)return setMsg('Usuario o contraseña incorrectos');if(remember)localStorage.setItem('jumati_remember',JSON.stringify(auth));else localStorage.removeItem('jumati_remember');setCurrent(u);go('menu')};
 const register=e=>{e.preventDefault();if(!form.name||!form.user||!form.password)return setMsg('Completa todos los datos');if(getUsers().some(u=>u.user.toLowerCase()===form.user.toLowerCase()))return setMsg('Ese usuario ya existe');const u={...form};saveUser(u);login(u.user,u.password);setCurrent(u);go('menu')};
 const completePuzzle=()=>{const p=getProgress(current.user),id=`${selectedPuzzle.id}-${difficulty}`;if(!p.completed.includes(id)){p.completed.push(id);p.stars+=3;saveProgress(current.user,p)}setScreen('complete')};
 const newMath=()=>{const item=randomObject();let a=1+Math.floor(Math.random()*8),b=1+Math.floor(Math.random()*5),op='+';if(gameType==='sub'){if(b>a)[a,b]=[b,a];op='-'}if(gameType==='count'){a=1+Math.floor(Math.random()*9);b=0;op='count'}if(gameType==='seq'){a=1+Math.floor(Math.random()*4);b=1+Math.floor(Math.random()*2);op='seq'}setMath({a,b,op,answer:'',feedback:'',item,locked:false});setTimeout(()=>speakMathInstruction(gameType,current?.gender,a,b,item),180)};
 const expected=()=>math.op==='+'?math.a+math.b:math.op==='-'?math.a-math.b:math.op==='count'?math.a:math.a+math.b*2;
 const checkMath=()=>{if(math.locked)return;if(Number(math.answer)===expected()){correctSound();speakCorrect(current?.gender);const p=getProgress(current.user);p.mathCorrect+=1;p.stars+=1;saveProgress(current.user,p);setMath({...math,feedback:'correct',locked:true})}else{wrongSound();speakWrong(current?.gender);setMath({...math,feedback:'wrong',locked:false})}};
 const startGame=type=>{setGameType(type);setMath(initialChallenge(type));go('math')};
 const shell=c=><main className="app"><section className="screen"><div className="cloud c1"/><div className="cloud c2"/>{c}<div className="ground"/></section></main>;

 if(screen==='home')return shell(<div className="center"><Logo/><h1>¡Bienvenido a JUMATI!</h1><p className="slogan">¡Juega, aprende y supera retos!</p><div className="characters"><b>👦</b><b className="lion">🦁</b><b>👧</b></div><div className="actions"><button className="btn blue" onClick={()=>go('login')}>▶ Iniciar sesión</button><button className="btn green" onClick={()=>go('register')}>✨ Crear cuenta</button></div><p className="pill">⭐ Pequeños retos, grandes logros ⭐</p></div>);
 if(screen==='login')return shell(<div className="card-wrap"><button className="back" onClick={()=>go('home')}>←</button><Logo/><form className="card" onSubmit={doLogin}><div className="avatar-top">🦁</div><h2>¡Hola de nuevo!</h2><p>Ingresa para seguir jugando</p><label>👤 Usuario</label><input value={auth.user} onChange={e=>setAuth({...auth,user:e.target.value})}/><label>🔐 Contraseña</label><div className="password-box"><input type={showPassword?'text':'password'} value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><button type="button" aria-label="Mostrar u ocultar contraseña" onClick={()=>setShowPassword(v=>!v)}>{showPassword?'🙈':'👁️'}</button></div><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Recordar contraseña</span></label>{msg&&<div className="error">{msg}</div>}<button className="btn blue">▶ Ingresar</button><button type="button" className="link" onClick={()=>go('register')}>¿No tienes cuenta? <b>Crear cuenta</b></button></form></div>);
 if(screen==='register')return shell(<div className="card-wrap wide"><button className="back" onClick={()=>go('home')}>←</button><Logo/><form className="card" onSubmit={register}><h2>✨ Crea tu personaje</h2><div className="grid"><div><label>Nombre</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label>Usuario</label><input value={form.user} onChange={e=>setForm({...form,user:e.target.value})}/></div><div><label>Contraseña</label><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div><label>Edad</label><select value={form.age} onChange={e=>setForm({...form,age:e.target.value})}><option>4</option><option>5</option><option>6</option></select></div></div><h3>Elige tu perfil</h3><div className="choice"><button type="button" className={form.gender==='nino'?'selected':''} onClick={()=>setForm({...form,gender:'nino',avatar:'🧒'})}>👦 Niño</button><button type="button" className={form.gender==='nina'?'selected pink':''} onClick={()=>setForm({...form,gender:'nina',avatar:'👧'})}>👧 Niña</button></div><div className="avatars">{(form.gender==='nina'?['👧','👸','🧚','🐰']:['🧒','🦁','🦸','🧑‍🚀']).map(a=><button type="button" key={a} className={form.avatar===a?'selected':''} onClick={()=>setForm({...form,avatar:a})}>{a}</button>)}</div>{msg&&<div className="error">{msg}</div>}<button className="btn green">Crear mi cuenta</button></form></div>);
 if(screen==='menu')return shell(<div className="center menu"><Logo/><div className="profile"><span>{current?.avatar}</span><div><b>¡Hola, {current?.name}!</b><small>{current?.age} años</small></div><strong>⭐ {progress.stars}</strong></div><div className="menu-grid"><button onClick={()=>go('games')}>🎮<b>Jugar</b></button><button onClick={()=>go('puzzles')}>🧩<b>Rompecabezas</b></button><button onClick={()=>go('achievements')}>🏆<b>Mis logros</b></button><button onClick={()=>go('progress')}>📊<b>Mi progreso</b></button></div><div className="menu-actions"><button className="logout-btn" onClick={()=>{logout();setCurrent(null);stopMusic();go('home')}}>🚪 Cerrar sesión</button></div></div>);
 if(screen==='games')return shell(<div className="center catalog"><button className="back" onClick={()=>go('menu')}>←</button><h1>🎮 Elige un juego</h1><p>Aprende jugando y gana estrellas</p><div className="game-grid"><button onClick={()=>startGame('sum')}><span>➕</span><b>Sumas</b><small>Junta cantidades</small></button><button onClick={()=>startGame('sub')}><span>➖</span><b>Restas</b><small>Quita y descubre</small></button><button onClick={()=>startGame('count')}><span>🍎</span><b>Contar</b><small>Cuenta los dibujos</small></button><button onClick={()=>startGame('seq')}><span>🔢</span><b>Series</b><small>Completa la secuencia</small></button></div></div>);
 if(screen==='puzzles')return shell(<div className="center catalog"><button className="back" onClick={()=>go('menu')}>←</button><h1>🧩 Elige tu rompecabezas</h1><p>15 dibujos diferentes para jugar</p><div className="puzzle-grid">{puzzleList(current?.gender).map(x=><button key={x.id} onClick={()=>{setSelectedPuzzle(x);go('difficulty')}}><span>{x.icon}</span><b>{x.index+1}. {x.name}</b></button>)}</div></div>);
 if(screen==='difficulty')return shell(<div className="center"><button className="back" onClick={()=>go('puzzles')}>←</button><h1>{selectedPuzzle?.icon} {selectedPuzzle?.name}</h1><h2>¿Cuántas piezas quieres?</h2><div className="difficulty">{difficulties.map(n=><button key={n} onClick={()=>{setDifficulty(n);setPuzzleKey(k=>k+1);go('playPuzzle')}}><b>{n}</b><small>piezas</small></button>)}</div><p className="pill">🦁 A mayor número de piezas, mayor desafío</p></div>);
 if(screen==='playPuzzle')return <PuzzleGame key={puzzleKey} puzzle={selectedPuzzle} gender={current.gender} count={difficulty} onBack={()=>go('difficulty')} onComplete={completePuzzle}/>;
 if(screen==='complete')return shell(<div className="center"><div className="celebrate">🎉</div><h1>¡COMPLETADO!</h1><h2>{selectedPuzzle?.name}</h2><div className="stars-big">⭐⭐⭐</div><p className="pill">Ganaste +3 estrellas</p><div className="actions"><button className="btn green" onClick={()=>go('puzzles')}>▶️ Siguiente rompecabezas</button><button className="btn blue" onClick={()=>go('menu')}>🏠 Volver al menú</button></div></div>);
 if(screen==='math'){
   const title={sum:'➕ Sumas divertidas',sub:'➖ Restas divertidas',count:`${math.item.icon} Cuenta los ${math.item.many}`,seq:'🔢 Completa la serie'}[gameType];
   let q;
   if(math.op==='count')q=<div className="object-cloud">{Array.from({length:math.a},(_,i)=><span key={i}>{math.item.icon}</span>)}</div>;
   else if(math.op==='seq')q=<div className="series-row numeric-series"><span>{math.a}</span><b>→</b><span>{math.a+math.b}</span><b>→</b><span className="question-bubble">?</span></div>;
   else q=<div className="visual-operation"><span>{math.item.icon.repeat(math.a)}</span><b>{math.op}</b><span>{math.item.icon.repeat(math.b)}</span><b>= ?</b></div>;
   return shell(<div className="center"><button className="back" onClick={()=>go('games')}>←</button><h1>{title}</h1><div className="math-card"><div className="math-question">{q}</div><input className="math-answer" disabled={math.locked} inputMode="numeric" placeholder="?" value={math.answer} onChange={e=>!math.locked&&setMath({...math,answer:e.target.value,feedback:''})}/>{math.feedback==='correct'&&<p className="good">⭐ ¡CORRECTO! +1 estrella</p>}{math.feedback==='wrong'&&<p className="bad">💪 ¡Inténtalo otra vez!</p>}{!math.locked&&<button className="btn green" onClick={checkMath}>✓ Comprobar</button>}{math.locked&&<button className="btn blue next-challenge" onClick={newMath}>▶️ Siguiente reto</button>}</div></div>)};
 if(screen==='achievements')return shell(<div className="center catalog"><button className="back" onClick={()=>go('menu')}>←</button><h1>🏆 Mis logros</h1><div className="achievement-grid"><div className={progress.mathCorrect>=1?'earned':''}>🌟<b>Primer acierto</b><small>Resuelve 1 reto matemático</small></div><div className={progress.mathCorrect>=10?'earned':''}>🧠<b>Mente brillante</b><small>10 retos matemáticos</small></div><div className={progress.completed.length>=1?'earned':''}>🧩<b>Primer puzzle</b><small>Completa 1 rompecabezas</small></div><div className={progress.completed.length>=5?'earned':''}>🏅<b>Maestro puzzle</b><small>Completa 5 rompecabezas</small></div><div className={progress.stars>=20?'earned':''}>⭐<b>Coleccionista</b><small>Consigue 20 estrellas</small></div><div className={progress.stars>=50?'earned':''}>👑<b>Campeón JUMATI</b><small>Consigue 50 estrellas</small></div></div></div>);
 if(screen==='progress'){const mathPct=Math.min(100,progress.mathCorrect*5),puzPct=Math.min(100,Math.round(progress.completed.length/15*100));return shell(<div className="center catalog"><button className="back" onClick={()=>go('menu')}>←</button><h1>📊 Mi progreso</h1><div className="stats"><div><b>⭐ {progress.stars}</b><small>Estrellas</small></div><div><b>🧩 {progress.completed.length}</b><small>Rompecabezas</small></div><div><b>🎮 {progress.mathCorrect}</b><small>Retos correctos</small></div></div><div className="progress-card"><b>🎮 Juegos matemáticos</b><div className="progress-bar"><i style={{width:`${mathPct}%`}}/></div><small>{mathPct}%</small><b>🧩 Rompecabezas</b><div className="progress-bar"><i style={{width:`${puzPct}%`}}/></div><small>{puzPct}%</small></div></div>)};
 return null;
}

function PuzzleGame({puzzle,gender,count,onBack,onComplete}){
 useEffect(()=>{startMusic((puzzle?.index||0)+(gender==='nina'?4:0));const t=setTimeout(()=>speakPuzzleInstruction(gender),350);return()=>{clearTimeout(t);stopMusic();window.speechSynthesis?.cancel();}},[puzzle,gender]);
 const [cols,rows]=gridFor[count],total=cols*rows,image=useMemo(()=>puzzleSvgData(puzzle,gender),[puzzle,gender]);
 const [placed,setPlaced]=useState(()=>Array(total).fill(false)),[pieces,setPieces]=useState(()=>shuffle(Array.from({length:total},(_,i)=>i))),[selected,setSelected]=useState(null),[done,setDone]=useState(false),[guideTarget,setGuideTarget]=useState(null);
 const place=(piece,target)=>{if(done)return;if(piece!==target){wrongSound();return;}pieceSound();setPlaced(p=>{const n=[...p];n[target]=true;if(n.every(Boolean)){setDone(true);winSound();speakPuzzleComplete(gender);setTimeout(onComplete,2100)}return n});setPieces(p=>p.filter(x=>x!==piece));setSelected(null);setGuideTarget(null)};
 const dragStart=(e,i)=>{setSelected(i);setGuideTarget(i);e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move'};
 const drop=(e,target)=>{e.preventDefault();place(Number(e.dataTransfer.getData('text/plain')),target)};
 const reset=()=>{setPlaced(Array(total).fill(false));setPieces(shuffle(Array.from({length:total},(_,i)=>i)));setSelected(null);setGuideTarget(null);setDone(false);speakPuzzleInstruction(gender)};
 return <main className="app"><section className="screen puzzle-screen"><button className="back" onClick={onBack}>←</button><div className="puzzle-page"><div className="puzzle-head"><div><b>{puzzle.icon} {puzzle.name}</b><small>{count} piezas</small></div><strong>🧩 {placed.filter(Boolean).length}/{total}</strong></div><div className="puzzle-layout"><div className="board" style={{gridTemplateColumns:`repeat(${cols},1fr)`,gridTemplateRows:`repeat(${rows},1fr)`,aspectRatio:'10 / 7'}}>{Array.from({length:total},(_,i)=><div key={i} className={`slot ${placed[i]?'filled':''} ${guideTarget===i?'guide-target':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,i)} onClick={()=>selected!==null&&place(selected,i)}>{placed[i]?<Piece i={i} cols={cols} rows={rows} image={image}/>:<Piece i={i} cols={cols} rows={rows} image={image} guide/>}</div>)}</div><div className="tray"><div className="puzzle-tools"><button className="reset-only" onClick={reset}>🔄 Reiniciar</button></div><div className="pieces">{pieces.map(i=><div key={i} draggable onDragStart={e=>dragStart(e,i)} onClick={()=>{setSelected(i);setGuideTarget(i);speak('¡Muy bien! Coloca la pieza donde está brillando.',gender,{rate:1.05});setTimeout(()=>setGuideTarget(t=>t===i?null:t),2600)}} className={`piece-wrap ${selected===i?'selected-piece':''}`}><Piece i={i} cols={cols} rows={rows} image={image}/></div>)}</div><p className="touch-help">👆 Toca una pieza y JUMATI iluminará automáticamente el lugar donde va.</p></div></div></div></section></main>;
}
function Piece({i,cols,rows,image,guide=false}){const x=i%cols,y=Math.floor(i/cols);return <div className={`piece ${guide?'guide-piece':''}`} style={{backgroundImage:`url("${image}")`,backgroundSize:`${cols*100}% ${rows*100}%`,backgroundPosition:`${cols===1?0:(x/(cols-1))*100}% ${rows===1?0:(y/(rows-1))*100}%`}}/>}
export default App;
